#!/usr/bin/env python3
"""RTKG Temporal Graph-RAG over JSON snapshots with Ollama.

V2 improvements:
- Supports the metric names generated by build_rtkg_snapshots.py:
  cpu_usage_max, memory_working_set_max_bytes, network_receive_bytes_max,
  average_latency_mean, request_rate_mean, etc.
- Computes deterministic graph answers before calling the LLM.
- Sends the computed answer to the LLM so it explains evidence instead of guessing.
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import requests

NULLISH = {"", "none", "null", "nan", "na", "n/a", "unknown"}
NORMAL_LABELS = {"normal", "healthy", "ok", "false", "0", "no", "none", "nan", "null", "nominal"}
UNHEALTHY_LABELS = {"unhealthy", "degraded", "abnormal", "anomalous", "anomaly", "critical", "warning", "error", "failed", "failure"}

CPU_ALIASES = [
    "cpu_usage_max", "cpu_usage_mean", "cpu_system_max", "cpu_system_mean",
    "cpu", "cpu_usage", "CPU", "cpu_percent", "cpu_pct", "cpu_usage_percent", "cpu_usage_pct",
    "container_cpu_usage_seconds_total", "container_cpu_system_seconds_total", "pu_usage_max"
]
MEMORY_ALIASES = [
    "memory_working_set_max_bytes", "memory_working_set_mean_bytes",
    "memory_rss_max_bytes", "memory_rss_mean_bytes",
    "memory", "memory_usage", "Memory", "mem", "rss",
    "container_memory_working_set_bytes", "container_memory_rss"
]
NET_RX_ALIASES = [
    "network_receive_bytes_max", "network_receive_bytes_mean",
    "net_rx", "network_rx", "rx_bytes", "net_receive", "network_receive_bytes_total",
    "container_network_receive_bytes_total"
]
ERROR_RATE_ALIASES = ["error_rate", "errorRate", "errors", "error_count"]
LATENCY_ALIASES = [
    "average_latency_mean", "p99_latency_mean", "p90_latency_mean", "p50_latency_mean",
    "latency", "avg_latency", "duration", "response_time", "p95_latency"
]
REQUEST_RATE_ALIASES = [
    "request_rate_mean", "new_request", "total_request",
    "request_rate", "requests_per_second", "rps", "request_count", "requests"
]


def safe_float(value: Any, default: float = 0.0) -> float:
    if value is None:
        return default
    try:
        if isinstance(value, str):
            value = value.strip().replace("%", "")
            if value.lower() in NULLISH:
                return default
        x = float(value)
        if math.isnan(x) or math.isinf(x):
            return default
        return x
    except Exception:
        return default


def numeric_from_attrs(attrs: Dict[str, Any], aliases: Iterable[str], default: float = 0.0) -> float:
    if not isinstance(attrs, dict):
        return default
    for key in aliases:
        if key in attrs:
            return safe_float(attrs.get(key), default)
    norm = {re.sub(r"[^a-z0-9]", "", str(k).lower()): k for k in attrs.keys()}
    for key in aliases:
        nk = re.sub(r"[^a-z0-9]", "", str(key).lower())
        if nk in norm:
            return safe_float(attrs.get(norm[nk]), default)
    return default


def first_present(d: Dict[str, Any], keys: Iterable[str], default: Any = None) -> Any:
    for k in keys:
        if k in d and d[k] is not None:
            return d[k]
    return default


def normalize_service_name(name: Any) -> str:
    if name is None:
        return "unknown"
    s = str(name).strip()
    if not s:
        return "unknown"
    s = re.sub(r"-[a-f0-9]{8,10}-[a-z0-9]{5}$", "", s)
    s = re.sub(r"-[a-z0-9]{5,}$", "", s) if len(s.split("-")) > 3 else s
    return s


def parse_datetime(value: Any) -> Optional[datetime]:
    if not value:
        return None
    s = str(value).strip()
    if not s:
        return None
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(s)
        if dt.tzinfo is not None:
            dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
        return dt
    except Exception:
        pass
    for fmt in ["%Y-%m-%d %H:%M:%S", "%Y-%m-%d_%H-%M-%S", "%Y%m%dT%H%M%S", "%Y%m%d-%H%M%S"]:
        try:
            return datetime.strptime(s, fmt)
        except Exception:
            continue
    return None


def timestamp_from_file(path: Path) -> Optional[datetime]:
    name = path.name
    for pat in [r"(\d{8})T(\d{6})", r"(\d{8})-(\d{6})", r"(\d{4}-\d{2}-\d{2})[_T ](\d{2})[-:](\d{2})[-:](\d{2})"]:
        m = re.search(pat, name)
        if not m:
            continue
        if len(m.groups()) == 2:
            return parse_datetime(f"{m.group(1)}T{m.group(2)}")
        return parse_datetime(f"{m.group(1)} {m.group(2)}:{m.group(3)}:{m.group(4)}")
    return None


def label_is_anomalous(label: Any) -> bool:
    if label is None:
        return False
    s = str(label).strip().lower()
    if s in NORMAL_LABELS or s in NULLISH:
        return False
    try:
        return safe_float(s) != 0.0
    except Exception:
        return True


def edge_is_unhealthy(attrs: Dict[str, Any]) -> bool:
    label = first_present(attrs, ["edge_status", "communication_anomaly", "status", "health", "prediction", "anomaly", "label"], None)
    if label is not None:
        s = str(label).strip().lower()
        if s in NORMAL_LABELS:
            return False
        if s in UNHEALTHY_LABELS or label_is_anomalous(label):
            return True
    return numeric_from_attrs(attrs, ERROR_RATE_ALIASES, 0.0) > 0


def parse_time_window(query: str, default_minutes: int = 5) -> timedelta:
    q = query.lower()
    patterns = [
        (r"(?:last|past|previous)\s+(\d+)\s*(seconds|second|sec|secs|s)\b", "seconds"),
        (r"(?:last|past|previous)\s+(\d+)\s*(minutes|minute|mins|min|m)\b", "minutes"),
        (r"(?:last|past|previous)\s+(\d+)\s*(hours|hour|hrs|hr|h)\b", "hours"),
    ]
    for pat, unit in patterns:
        m = re.search(pat, q)
        if m:
            n = int(m.group(1))
            return timedelta(**{unit: n})
    return timedelta(minutes=default_minutes)


def compact_json(obj: Any, max_chars: int = 30000) -> str:
    text = json.dumps(obj, indent=2, ensure_ascii=False, default=str)
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "\n...TRUNCATED..."


class RTKGGraphRAG:
    def __init__(self, snapshots_dir: str, model: str, ollama_url: str, default_minutes: int, top_k: int, temperature: float, num_ctx: int):
        self.snapshots_dir = Path(snapshots_dir)
        self.model = model
        self.ollama_url = ollama_url.rstrip("/")
        self.default_minutes = default_minutes
        self.top_k = top_k
        self.temperature = temperature
        self.num_ctx = num_ctx

    def load_snapshots(self) -> List[Dict[str, Any]]:
        files = sorted([p for p in self.snapshots_dir.glob("*.json") if p.name.lower() not in {"index.json", "metadata.json"}])
        snaps = []
        for p in files:
            try:
                data = json.loads(p.read_text(encoding="utf-8"))
                ts = parse_datetime(data.get("timestamp")) or parse_datetime(data.get("window", {}).get("start")) or timestamp_from_file(p)
                if ts is None:
                    print(f"[WARN] no timestamp for {p.name}", file=sys.stderr)
                    continue
                snaps.append({"path": p, "timestamp": ts, "data": data})
            except Exception as e:
                print(f"[WARN] cannot read {p.name}: {e}", file=sys.stderr)
        snaps.sort(key=lambda s: s["timestamp"])
        return snaps

    def retrieve(self, question: str) -> List[Dict[str, Any]]:
        snaps = self.load_snapshots()
        if not snaps:
            return []
        window = parse_time_window(question, self.default_minutes)
        latest = snaps[-1]["timestamp"]
        start = latest - window
        return [s for s in snaps if start <= s["timestamp"] <= latest]

    def iter_microservice_nodes(self, snap: Dict[str, Any]):
        for node in snap["data"].get("nodes", []):
            if not isinstance(node, dict):
                continue
            attrs = node.get("attributes") if isinstance(node.get("attributes"), dict) else {}
            ntype = str(node.get("type", "")).lower()
            node_id = node.get("id") or node.get("name") or node.get("pod") or node.get("microservice")
            if not node_id:
                continue
            if ntype in {"pod", "microservice", "service", "container"} or any(k in attrs for k in CPU_ALIASES + MEMORY_ALIASES + ["anomaly"]):
                yield normalize_service_name(node_id), attrs

    def iter_edges(self, snap: Dict[str, Any]):
        for edge in snap["data"].get("edges", []):
            if not isinstance(edge, dict):
                continue
            attrs = edge.get("attributes") if isinstance(edge.get("attributes"), dict) else {}
            etype = str(edge.get("type", edge.get("relation", ""))).lower()
            src = edge.get("source") or edge.get("src") or edge.get("from") or edge.get("caller")
            dst = edge.get("target") or edge.get("dst") or edge.get("to") or edge.get("callee")
            if src and dst:
                yield normalize_service_name(src), normalize_service_name(dst), etype, attrs

    def build_evidence(self, question: str) -> Dict[str, Any]:
        selected = self.retrieve(question)
        if not selected:
            return {"status": "no_data", "query": question, "message": "No snapshots found for the requested time window."}

        service_stats = defaultdict(lambda: {
            "observed_snapshots": 0, "node_anomalous_snapshots": 0, "edge_unhealthy_incidents_connected_to_service": 0,
            "anomaly_types": Counter(), "cpu_values": [], "memory_values": [], "net_rx_values": [], "sample_anomaly_timestamps": []
        })

        for snap in selected:
            seen = set()
            for service, attrs in self.iter_microservice_nodes(snap):
                if service in seen:
                    continue
                seen.add(service)
                label = first_present(attrs, ["anomaly", "resource_anomaly", "anomaly_type", "Abnormality class", "abnormality_class", "status", "label", "class"], "Normal")
                cpu = numeric_from_attrs(attrs, CPU_ALIASES)
                mem = numeric_from_attrs(attrs, MEMORY_ALIASES)
                net = numeric_from_attrs(attrs, NET_RX_ALIASES)
                d = service_stats[service]
                d["observed_snapshots"] += 1
                d["cpu_values"].append(cpu)
                d["memory_values"].append(mem)
                d["net_rx_values"].append(net)
                if label_is_anomalous(label):
                    d["node_anomalous_snapshots"] += 1
                    d["anomaly_types"][str(label)] += 1
                    if len(d["sample_anomaly_timestamps"]) < 5:
                        d["sample_anomaly_timestamps"].append(snap["timestamp"].isoformat())

        edge_stats = defaultdict(lambda: {
            "observed_snapshots": 0, "unhealthy_snapshots": 0, "error_values": [], "latency_values": [], "request_values": [], "statuses": Counter(), "sample_unhealthy_timestamps": []
        })
        for snap in selected:
            for src, dst, etype, attrs in self.iter_edges(snap):
                if etype and etype not in {"communication", "calls", "call", "http", "grpc", ""}:
                    continue
                key = (src, dst)
                status = first_present(attrs, ["edge_status", "communication_anomaly", "status", "health", "prediction", "anomaly", "label"], "unknown")
                err = numeric_from_attrs(attrs, ERROR_RATE_ALIASES)
                lat = numeric_from_attrs(attrs, LATENCY_ALIASES)
                req = numeric_from_attrs(attrs, REQUEST_RATE_ALIASES)
                e = edge_stats[key]
                e["observed_snapshots"] += 1
                e["statuses"][str(status)] += 1
                e["error_values"].append(err)
                e["latency_values"].append(lat)
                e["request_values"].append(req)
                if edge_is_unhealthy(attrs):
                    e["unhealthy_snapshots"] += 1
                    service_stats[src]["edge_unhealthy_incidents_connected_to_service"] += 1
                    service_stats[dst]["edge_unhealthy_incidents_connected_to_service"] += 1
                    if len(e["sample_unhealthy_timestamps"]) < 5:
                        e["sample_unhealthy_timestamps"].append(snap["timestamp"].isoformat())

        service_rows = []
        for service, d in service_stats.items():
            total = max(1, d["observed_snapshots"])
            cpu_values = d["cpu_values"] or [0]
            mem_values = d["memory_values"] or [0]
            net_values = d["net_rx_values"] or [0]
            service_rows.append({
                "microservice": service,
                "observed_snapshots": d["observed_snapshots"],
                "node_anomalous_snapshots": d["node_anomalous_snapshots"],
                "node_anomaly_rate": round(d["node_anomalous_snapshots"] / total, 4),
                "node_anomaly_rate_percent": round(100 * d["node_anomalous_snapshots"] / total, 2),
                "edge_unhealthy_incidents_connected_to_service": d["edge_unhealthy_incidents_connected_to_service"],
                "combined_anomaly_evidence_score": d["node_anomalous_snapshots"] + d["edge_unhealthy_incidents_connected_to_service"],
                "anomaly_types": dict(d["anomaly_types"]),
                "max_cpu": round(max(cpu_values), 6),
                "avg_cpu": round(sum(cpu_values) / len(cpu_values), 6),
                "max_memory": round(max(mem_values), 3),
                "avg_memory": round(sum(mem_values) / len(mem_values), 3),
                "max_net_rx": round(max(net_values), 3),
                "sample_anomaly_timestamps": d["sample_anomaly_timestamps"],
            })

        edge_rows = []
        for (src, dst), e in edge_stats.items():
            total = max(1, e["observed_snapshots"])
            errs = e["error_values"] or [0]
            lats = e["latency_values"] or [0]
            reqs = e["request_values"] or [0]
            edge_rows.append({
                "edge": f"{src} -> {dst}",
                "source": src,
                "target": dst,
                "observed_snapshots": e["observed_snapshots"],
                "unhealthy_snapshots": e["unhealthy_snapshots"],
                "unhealthy_rate_percent": round(100 * e["unhealthy_snapshots"] / total, 2),
                "max_error_rate": round(max(errs), 6),
                "avg_error_rate": round(sum(errs) / len(errs), 6),
                "max_latency": round(max(lats), 6),
                "avg_latency": round(sum(lats) / len(lats), 6),
                "max_request_rate": round(max(reqs), 6),
                "statuses": dict(e["statuses"]),
                "sample_unhealthy_timestamps": e["sample_unhealthy_timestamps"],
            })

        events = []
        affected = Counter()
        for snap in selected:
            for node in snap["data"].get("nodes", []):
                if not isinstance(node, dict):
                    continue
                if str(node.get("type", "")).lower() not in {"runtime_event", "event", "kubernetes_event"}:
                    continue
                attrs = node.get("attributes", {}) if isinstance(node.get("attributes"), dict) else {}
                pod = normalize_service_name(first_present(attrs, ["pod", "affected_microservice", "affected_service", "involved_object", "object", "service"], "unknown"))
                affected[pod] += 1
                events.append({
                    "timestamp": snap["timestamp"].isoformat(),
                    "event_id": node.get("id", "event"),
                    "reason": str(first_present(attrs, ["reason", "event_reason", "type", "event_type"], "event")),
                    "affected_microservice": pod,
                    "message": str(first_present(attrs, ["message", "note", "description"], ""))[:250],
                })

        rankings = {
            "top_microservices_by_node_anomaly_rate": sorted(service_rows, key=lambda r: (r["node_anomaly_rate"], r["node_anomalous_snapshots"]), reverse=True)[:self.top_k],
            "top_microservices_by_combined_anomaly_evidence": sorted(service_rows, key=lambda r: r["combined_anomaly_evidence_score"], reverse=True)[:self.top_k],
            "top_microservices_by_cpu": sorted(service_rows, key=lambda r: r["max_cpu"], reverse=True)[:self.top_k],
            "top_microservices_by_memory": sorted(service_rows, key=lambda r: r["max_memory"], reverse=True)[:self.top_k],
            "top_unhealthy_communication_edges": sorted(edge_rows, key=lambda r: (r["unhealthy_rate_percent"], r["unhealthy_snapshots"]), reverse=True)[:self.top_k],
            "top_edges_by_error_rate": sorted(edge_rows, key=lambda r: r["max_error_rate"], reverse=True)[:self.top_k],
            "top_edges_by_latency": sorted(edge_rows, key=lambda r: r["max_latency"], reverse=True)[:self.top_k],
            "top_event_affected_microservices": [{"microservice": k, "event_count": v} for k, v in affected.most_common(self.top_k)],
        }

        return {
            "status": "ok",
            "query": question,
            "retrieval_source": "Runtime Temporal Knowledge Graph JSON snapshots",
            "retrieval_type": "Temporal Graph-RAG",
            "retrieval_window": {
                "start": selected[0]["timestamp"].isoformat(),
                "end": selected[-1]["timestamp"].isoformat(),
                "num_snapshots": len(selected),
            },
            "graph_summary": {
                "num_microservices_observed": len(service_rows),
                "num_communication_edges_observed": len(edge_rows),
                "num_events": len(events),
            },
            "rankings": rankings,
            "recent_events": sorted(events, key=lambda x: x["timestamp"], reverse=True)[:self.top_k],
        }

    def direct_answer(self, question: str, evidence: Dict[str, Any]) -> str:
        if evidence.get("status") != "ok":
            return evidence.get("message", "No evidence available.")
        q = question.lower()
        w = evidence["retrieval_window"]
        prefix = f"In {w['num_snapshots']} RTKG snapshots from {w['start']} to {w['end']}, "
        r = evidence["rankings"]
        if "cpu" in q or "pu_usage" in q:
            rows = [x for x in r["top_microservices_by_cpu"] if x["max_cpu"] > 0 or x["avg_cpu"] > 0]
            if not rows:
                return prefix + "no non-zero CPU values were found in the retrieved evidence."
            x = rows[0]
            return prefix + f"{x['microservice']} has the highest CPU usage with max_cpu={x['max_cpu']} and avg_cpu={x['avg_cpu']}."
        if "memory" in q or "mem" in q:
            rows = [x for x in r["top_microservices_by_memory"] if x["max_memory"] > 0 or x["avg_memory"] > 0]
            if not rows:
                return prefix + "no non-zero memory values were found in the retrieved evidence."
            x = rows[0]
            return prefix + f"{x['microservice']} has the highest memory usage with max_memory={x['max_memory']} bytes and avg_memory={x['avg_memory']} bytes."
        if "error" in q:
            rows = [x for x in r["top_edges_by_error_rate"] if x["max_error_rate"] > 0 or x["avg_error_rate"] > 0]
            if not rows:
                return prefix + "no edge with positive error rate was found."
            x = rows[0]
            return prefix + f"{x['edge']} has the highest error rate with max_error_rate={x['max_error_rate']} and avg_error_rate={x['avg_error_rate']}."
        if "latency" in q:
            rows = [x for x in r["top_edges_by_latency"] if x["max_latency"] > 0 or x["avg_latency"] > 0]
            if not rows:
                return prefix + "no non-zero latency values were found in the retrieved evidence."
            x = rows[0]
            return prefix + f"{x['edge']} has the highest latency with max_latency={x['max_latency']} and avg_latency={x['avg_latency']}."
        if "anomaly" in q or "anomalies" in q:
            rows = [x for x in r["top_microservices_by_node_anomaly_rate"] if x["node_anomalous_snapshots"] > 0]
            if not rows:
                return prefix + "no node anomalies were found."
            x = rows[0]
            return prefix + f"{x['microservice']} has the highest node anomaly rate: {x['node_anomaly_rate_percent']}% ({x['node_anomalous_snapshots']}/{x['observed_snapshots']} snapshots), anomaly_types={x['anomaly_types']}."
        return "Summarize the retrieved RTKG evidence relevant to the question."

    def prompt(self, question: str, evidence: Dict[str, Any]) -> str:
        direct = self.direct_answer(question, evidence)
        return f"""
You are an expert SRE assistant for Kubernetes microservice observability.
You answer using Temporal Graph-RAG evidence from RTKG snapshots.

Rules:
- Use ONLY the evidence below.
- Do not invent microservices, timestamps, metrics, events, anomaly types, or causes.
- Prefer COMPUTED_DIRECT_ANSWER_FROM_GRAPH when it directly answers the question.
- Keep the answer concise and diagnostic.

COMPUTED_DIRECT_ANSWER_FROM_GRAPH:
{direct}

RTKG_EVIDENCE_JSON:
{compact_json(evidence)}

USER_QUESTION:
{question}

Answer:
""".strip()

    def ask(self, question: str, show_evidence: bool = False) -> Dict[str, Any]:
        evidence = self.build_evidence(question)
        payload = {
            "model": self.model,
            "prompt": self.prompt(question, evidence),
            "stream": False,
            "options": {"temperature": self.temperature, "num_ctx": self.num_ctx},
        }
        try:
            res = requests.post(f"{self.ollama_url}/api/generate", json=payload, timeout=180)
            if res.status_code == 200:
                answer = res.json().get("response", "")
            else:
                answer = f"Ollama error {res.status_code}: {res.text[:1000]}"
        except Exception as e:
            answer = f"Ollama error: {e}"
        out = {"model": self.model, "question": question, "answer": answer, "computed_direct_answer": self.direct_answer(question, evidence)}
        if show_evidence:
            out["evidence"] = evidence
        return out

    def list_models(self) -> List[str]:
        res = requests.get(f"{self.ollama_url}/api/tags", timeout=10)
        res.raise_for_status()
        return [m["name"] for m in res.json().get("models", [])]


def interactive(rag: RTKGGraphRAG, show_evidence: bool):
    print("RTKG Temporal Graph-RAG interactive mode")
    print("Commands: /models, /evidence on, /evidence off, /quit")
    print(f"Current model: {rag.model}\n")
    while True:
        try:
            q = input("Question> ").strip()
        except (KeyboardInterrupt, EOFError):
            print()
            break
        if not q:
            continue
        if q in {"/quit", "/exit", "quit", "exit"}:
            break
        if q == "/models":
            for m in rag.list_models():
                print(" -", m)
            continue
        if q.startswith("/model "):
            rag.model = q.split(" ", 1)[1].strip()
            print("Switched model to:", rag.model)
            continue
        if q.startswith("/evidence "):
            show_evidence = q.split(" ", 1)[1].strip().lower() in {"on", "true", "1", "yes"}
            print("Show evidence:", show_evidence)
            continue
        out = rag.ask(q, show_evidence=show_evidence)
        print("\nComputed graph answer:")
        print(out["computed_direct_answer"])
        print("\nLLM answer:")
        print(out["answer"].strip())
        if show_evidence:
            print("\nEvidence:")
            print(compact_json(out["evidence"], max_chars=20000))
        print()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--snapshots", required=True)
    ap.add_argument("--model", default="mistral:latest")
    ap.add_argument("--models", default=None, help="comma-separated models to compare")
    ap.add_argument("--ollama-url", default="http://127.0.0.1:11434")
    ap.add_argument("--default-minutes", type=int, default=5)
    ap.add_argument("--top-k", type=int, default=10)
    ap.add_argument("--temperature", type=float, default=0.0)
    ap.add_argument("--num-ctx", type=int, default=16384)
    ap.add_argument("--question", "-q", default=None)
    ap.add_argument("--show-evidence", action="store_true")
    args = ap.parse_args()

    rag = RTKGGraphRAG(args.snapshots, args.model, args.ollama_url, args.default_minutes, args.top_k, args.temperature, args.num_ctx)
    if args.question:
        models = [x.strip() for x in args.models.split(",")] if args.models else [args.model]
        for m in models:
            rag.model = m
            print("=" * 90)
            print("MODEL:", m)
            out = rag.ask(args.question, show_evidence=args.show_evidence)
            print("Computed graph answer:")
            print(out["computed_direct_answer"])
            print("\nLLM answer:")
            print(out["answer"].strip())
            if args.show_evidence:
                print("\nEvidence:")
                print(compact_json(out["evidence"], max_chars=20000))
        return
    interactive(rag, args.show_evidence)


if __name__ == "__main__":
    main()
